version: 2
jobs:
  build:
    docker:
      - image: jonathell/multi-manager:1.0
      
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: | 
            export SCANTIST_IMPORT_URL=https://api-staging.scantist.io/ci-scan/
            mvn install
            bash <(curl -s https://scripts.scantist.com/ci-circle.sh)  
