version: 2
jobs:
  build:
    docker:
      - image: jonathell/multi-manager:1.0
      
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: | 
      
            mvn install
            curl -s https://scripts.scantist.com/staging/scantist-bom-detect.jar --output scantist-bom-detect.jar
            java -jar scantist-bom-detect.jar
